---
title: "TDM Shortcut"
author: "Greg Macfarlane"
date: "3/30/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(foreign)
library(sf)
library(leaflet)
knitr::opts_chunk$set(echo = TRUE)
source("R/read_wfrcmag.R")
source("R/build_linknode_tables.R")
```


We gave up trying to make the all-streets network function. This builds
a network from the WFRC / MAG TDM model outputs.

We received a base 2019 scenario run of the WFRC / MAG model from MAG.

```{r read}
wfrc_links <- read_wfrcmag("data/v831_SE19_Net19__Summary_nodes.dbf",
                           "data/v831_SE19_Net19__Summary.dbf")
```

This file doesn't have all the roads, but it already has the free flow speed 
(I've converted it to meters per second), and capacity.
```{r show}
wfrc_links$links
```

```{r map}
pal <- colorQuantile("Reds", wfrc_links$links$capacity, n = 5)
leaflet(wfrc_links$links %>% st_transform(4326)) %>%
  addProviderTiles(providers$Esri.WorldGrayCanvas) %>%
  addPolylines(color = ~pal(capacity))
```

```{r write}
write_linknodes(wfrc_links, "data/wfrcmag")
```


